In [1]:
import numpy as np

In [2]:
#Write a NumPy program to create an array of 10 zeros
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Write a NumPy program to create an array of 10 ones
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#Write a NumPy program to reverse an array (first element becomes the last)
original = np.array([1, 2, 3, 4, 5])
reversed = np.flip(original)

print("Original:", original)
print("Reversed:", reversed)

Original: [1 2 3 4 5]
Reversed: [5 4 3 2 1]


In [10]:
#Write a NumPy program to extract all odd numbers from an array.
original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = original[original % 2 != 0]

print("Original array:", original)
print("Odd numbers:", odd_numbers)

Original array: [1 2 3 4 5 6 7 8 9]
Odd numbers: [1 3 5 7 9]


In [13]:
#Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array
original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mean = np.mean(original)
print('mean'"=",mean)

mean= 5.0


In [16]:
#Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.
original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
min_value = np.min(original)
max_value = np.max(original)

print("original:")
print(original)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

original:
[1 2 3 4 5 6 7 8 9]
Minimum value: 1
Maximum value: 9


In [17]:
first = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

second = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

third = np.dot(first, second)
print('first multiplied by second=',third)

first multiplied by second= [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [18]:
#Write a NumPy program to reverse the order of elements in each column of a 2D array
original = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
reversed = np.flipud(original)
print(reversed)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
