In [8]:
a=10
print(a,type(a))
a=10.2
print(a,type(a))
a="hello"
print(a,type(a))
a=True
print(a,type(a))
a=None
print(a,type(a))
a={1,2,3}
print(a,type(a))
a=[1,2,3]
print(a,type(a))
a=(1,2,3)
print(a,type(a))
a={'a':1,'b':2}
print(a,type(a))

10 <class 'int'>
10.2 <class 'float'>
hello <class 'str'>
True <class 'bool'>
None <class 'NoneType'>
{1, 2, 3} <class 'set'>
[1, 2, 3] <class 'list'>
(1, 2, 3) <class 'tuple'>
{'a': 1, 'b': 2} <class 'dict'>


In [9]:
#print
a=23
b=34
print("sum of a and b=",a+b)
print(a,b,a+b,sep='\n')

sum of a and b= 57
23
34
57


In [10]:
c=a+b
print(a,end=',')
print(b)
print(c)



23,34
57


In [11]:
for i in range(50):
    print(i,end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,

In [12]:
#del is used to delete the variable 

In [13]:
del print

NameError: name 'print' is not defined

In [ ]:
name="vinayak"
age=22
city="lucknow"
print(f'my name is{name},i am {age} year old,i live in {city}')

my name isvinayak,i am 22 year old,i live in lucknow


In [ ]:
x=10
y=54
z=x/y
print(f'{x}/{y}={z:.2f}')
#or
print(x,'/',y,"=",round(z,2))

10/54=0.19
10 / 54 = 0.19


In [ ]:
n1='sara'
n2='eliza'
n3='sam'
a1,a2,a3=22,23,23
print(f'{n1:10}{a1}')
print(f'{n2:10}{a2}')
print(f'{n3:10}{a3}')

sara      22
eliza     23
sam       23


In [ ]:
a=55
b=60
print(f"num ={a} and {b}")

num =55 and 60


In [ ]:
a=input("enter the name")
if len(a)==4:
    print("hello")
if len(a)==3:
    print("hello2")    
else:
    print("bye")    


bye


In [2]:
a= int(input('enter the number:'))
if a%2==0:
    print("num is even")

num is even


In [ ]:
a =int(input("enter a number"))
if a%2==0:
    print("a is even number") 
else:
    print("a is not even number")

a is not even number


In [ ]:
a,b,c=2,5,6
if a>b and a>c:
    print("a is greater")
elif b>a and b>c:
    print("b is greater")
else:
    print("c is greater")        

c is greater


In [ ]:
day= input("enter day:")
match(day):
    case 'monday': print("monday it is")
    case 'tuesday': print("tuesday it is")


In [ ]:
p=int(input("enter the principal:"))
r=int(input("enter the rate:"))
t=int(input("enter the time:"))
print("si =",p*r*t/100)

si = 1133.2


In [ ]:
for i in range(10):
   for j in range(i):
      print("h",end=' ')
   print('')  



h 
h h 
h h h 
h h h h 
h h h h h 
h h h h h h 
h h h h h h h 
h h h h h h h h 
h h h h h h h h h 


In [ ]:
#perfect square
a=1
while a<100:
    a_sum=0
    for i in range(1,a):
        if a%i==0:
            a_sum=a_sum+i
    if a_sum==a:
        print('perfect square number=',a)
    a=a+1     



perfect square number= 6
perfect square number= 28


In [ ]:
np=int(input('enter the new password:'))
for i in range(4):
    b=int(input('enter the password again:'))
    if b==np:
        print('new password created successfully')
        break
    else:
        print('passwords dont match')

passwords dont match
passwords dont match
passwords dont match
passwords dont match


In [ ]:
D={'NAME':'VINAYAK','AGE':23,'COURSE':'DELED','HOME':'LUCKNOW'}
print(D)

{'NAME': 'VINAYAK', 'AGE': 23, 'COURSE': 'DELED', 'HOME': 'LUCKNOW'}


In [ ]:
if 'NAME' in D:
    print(D['NAME'])
else:
    print('key is not present in D')    

VINAYAK


In [ ]:
D['harsh']=20
print(D)

{'NAME': 'VINAYAK', 'AGE': 23, 'COURSE': 'DELED', 'HOME': 'LUCKNOW', 'harsh': 20}


In [ ]:
D={'NAME':'VINAYAK','AGE':23,'COURSE':'DELED','HOME':'LUCKNOW'}
b=list(D)

print(b)

['NAME', 'AGE', 'COURSE', 'HOME']


In [ ]:
D={'NAME':'VINAYAK','AGE':23,'COURSE':'DELED','HOME':'LUCKNOW'}
for i in D:
   
    print(D[i])




VINAYAK
23
DELED
LUCKNOW


In [ ]:
import pandas as pd

series


In [ ]:
x=[3,4,5,6,7,8,9]
pd.Series(x)
var=pd.Series(x)
print(var)
print(type(var))

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3,4,5,6,7,8])

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a.ndim

1

In [ ]:
b=np.array([(1,2 ,3,4,5,6,7,8,),(1,2,3,4,5,6,7,8,)])

In [ ]:
b.ndim

2

In [ ]:
c=np.array([[(1,2 ,3,4,5,6,7,8,),(1,2,3,4,5,6,7,8,),(1,2,3,4,5,6,7,8)]])

In [ ]:
c.ndim

3

In [15]:
import numpy as np

# Create a 3D array (2x3x4)
array_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                     [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])


In [ ]:
f=np.ones((2,3))

In [ ]:
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
f.dtype

dtype('float64')

In [ ]:
f.ndim

2

In [19]:
v=np.full((3,3),20)

In [20]:
v

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [6]:
a =20
b=30
c=50
if a>b and b>c :
    print(a,"is greater that",b,c)
elif b>a and a>c:
    print(b,"is grater than",a,"amd",c)
else:
    print(c,"is greater than",b,"and",c)        

50 is greater than 30 and 50
