In [1]:
import numpy as np

In [18]:
np.set_printoptions(precision=2)

In [19]:
b= np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [20]:
a=np.array([1,2,3])
print(a)
print(a.shape)
print(b.ndim)

[1 2 3]
(3,)
2


In [10]:
c = np.array([
    [[1,2,3],
    [2,3,4],
    [2,2,2]],
    [[1,2,3],
    [2,3,4],
    [2,2,2]],
    ])

print(c)
print(c.shape)
print(c.dtype)

[[[1 2 3]
  [2 3 4]
  [2 2 2]]

 [[1 2 3]
  [2 3 4]
  [2 2 2]]]
(2, 3, 3)
int32


In [11]:
import numpy as np

c = np.array([
    [
        [[1, 2, 3],
         [2, 3, 4],
         [2, 2, 2]],

        [[1, 2, 3],
         [2, 3, 4],
         [2, 2, 2]]
    ],
    [
        [[4, 5, 6],
         [5, 6, 7],
         [6, 6, 6]],

        [[4, 5, 6],
         [5, 6, 7],
         [6, 6, 6]]
    ],
    [
        [[7, 8, 9],
         [8, 9, 10],
         [9, 9, 9]],

        [[7, 8, 9],
         [8, 9, 10],
         [9, 9, 9]]
    ]
])

print("4D Array:")
print(c)

4D Array:
[[[[ 1  2  3]
   [ 2  3  4]
   [ 2  2  2]]

  [[ 1  2  3]
   [ 2  3  4]
   [ 2  2  2]]]


 [[[ 4  5  6]
   [ 5  6  7]
   [ 6  6  6]]

  [[ 4  5  6]
   [ 5  6  7]
   [ 6  6  6]]]


 [[[ 7  8  9]
   [ 8  9 10]
   [ 9  9  9]]

  [[ 7  8  9]
   [ 8  9 10]
   [ 9  9  9]]]]


- generate matrix
* linear
* random

In [21]:
a= np.arange(1,10,0.02)
print(a)
a.size


[1.   1.02 1.04 1.06 1.08 1.1  1.12 1.14 1.16 1.18 1.2  1.22 1.24 1.26
 1.28 1.3  1.32 1.34 1.36 1.38 1.4  1.42 1.44 1.46 1.48 1.5  1.52 1.54
 1.56 1.58 1.6  1.62 1.64 1.66 1.68 1.7  1.72 1.74 1.76 1.78 1.8  1.82
 1.84 1.86 1.88 1.9  1.92 1.94 1.96 1.98 2.   2.02 2.04 2.06 2.08 2.1
 2.12 2.14 2.16 2.18 2.2  2.22 2.24 2.26 2.28 2.3  2.32 2.34 2.36 2.38
 2.4  2.42 2.44 2.46 2.48 2.5  2.52 2.54 2.56 2.58 2.6  2.62 2.64 2.66
 2.68 2.7  2.72 2.74 2.76 2.78 2.8  2.82 2.84 2.86 2.88 2.9  2.92 2.94
 2.96 2.98 3.   3.02 3.04 3.06 3.08 3.1  3.12 3.14 3.16 3.18 3.2  3.22
 3.24 3.26 3.28 3.3  3.32 3.34 3.36 3.38 3.4  3.42 3.44 3.46 3.48 3.5
 3.52 3.54 3.56 3.58 3.6  3.62 3.64 3.66 3.68 3.7  3.72 3.74 3.76 3.78
 3.8  3.82 3.84 3.86 3.88 3.9  3.92 3.94 3.96 3.98 4.   4.02 4.04 4.06
 4.08 4.1  4.12 4.14 4.16 4.18 4.2  4.22 4.24 4.26 4.28 4.3  4.32 4.34
 4.36 4.38 4.4  4.42 4.44 4.46 4.48 4.5  4.52 4.54 4.56 4.58 4.6  4.62
 4.64 4.66 4.68 4.7  4.72 4.74 4.76 4.78 4.8  4.82 4.84 4.86 4.88 4.9
 4.92 4.9

450

In [23]:
a= np.arange(-np.pi , np.pi,.25)
print(a)

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


In [25]:
b= np.linspace(1,10,100)
print(b)


[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [26]:
b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [27]:
b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [33]:
print(np.random.rand(3,3))

[[0.18 0.93 0.25]
 [0.48 0.8  0.28]
 [0.43 0.18 0.88]]


NameError: name 'x' is not defined